# ============================================================
# Plugins
# ============================================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# ============================================================
# General
# ============================================================
set -g prefix C-b

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set escape-time 0
set -g set-clipboard on
set-window-option -g mode-keys vi
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:RGB"

# ============================================================
# Keybinds
# ============================================================
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind -Tcopy-mode-vi WheelUpPane   send-keys -X scroll-up
bind -Tcopy-mode-vi WheelDownPane send-keys -X scroll-down
bind -Tcopy-mode-vi v             send -X begin-selection
bind -Tcopy-mode-vi y             send -X copy-pipe-and-cancel
bind -Tcopy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel

# ============================================================
# Clipboard
# ============================================================
set -s set-clipboard off

if-shell -b 'grep -qi microsoft /proc/version 2>/dev/null' {
  set -s copy-command "clip.exe"
}

if-shell -b '! grep -qi microsoft /proc/version 2>/dev/null && [ "$(uname)" = "Linux" ]' {
  set -s copy-command "xsel --clipboard --input"
}

if-shell -b '[ "$(uname)" = "Darwin" ]' {
  set -s copy-command "pbcopy"
}

# ============================================================
# Theme: Dracula
# ============================================================
set -g @dracula-plugins "git cpu-usage ram-usage time"
set -g @dracula-show-powerline true
set -g @dracula-refresh-rate 5

# ============================================================
# Resurrect / Continuum
# ============================================================
# set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'


